version: '3'

services:

  web:
    container_name: ismayil
    build: .
    restart: "always"
    env_file: .env
    environment:
      - VIRTUAL_HOST=kanankhalilov.com
      - VIRTUAL_PORT=8050
      - HTTP_PORT=8050
      - STATS_PORT=8051
    volumes:
      - .:/code
    ports:
      - "8050:8050"
    links:
      - postgres
    depends_on:
      - "postgres"

networks:
  default:
    external:
      name: nginx-proxy
